server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/admin
  profiles:
    active: default

kafka:
  topic:
    payment: payment-topic

KAFKA_BOOTSTRAP_SERVERS: kafka:19092
