server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:k2dv02l32P@my-mongodb:27017/admin
  kafka:
    bootstrap-servers: my-kafka:9092
  profiles:
    active: default

kafka:
  topic:
    payment: payment-topic
