server:
  port: 8080
spring:
  data:
    mongodb:
#      uri: mongodb://mongo-service:27017/admin
      uri: mongodb://root:example@${MONGODB_SERVICE_HOST:{{ include "pet-chart.fullname" . }}-mongodb}:27017/admin
