apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
        - name: pet-app
          image: valerykarpau/pet-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:19092
            - name: SPRING_PROFILES_ACTIVE
              value: default
