apiVersion: v1
kind: Service
metadata:
  name: {{ include "pet-chart.fullname" . }}-kafka
  labels:
    {{- include "pet-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    app: {{ include "pet-chart.fullname" . }}-kafka
