apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pet-chart.fullname" . }}-kafka
  labels:
    {{- include "pet-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "pet-chart.fullname" . }}-kafka
  template:
    metadata:
      labels:
        app: {{ include "pet-chart.fullname" . }}-kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image }}"
          imagePullPolicy: {{ .Values.kafka.pullPolicy }}
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "{{ .Values.kafka.environment.KAFKA_BROKER_ID }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ .Values.kafka.environment.KAFKA_ZOOKEEPER_CONNECT }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "{{ .Values.kafka.environment.KAFKA_ADVERTISED_LISTENERS }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "{{ .Values.kafka.environment.KAFKA_LISTENER_SECURITY_PROTOCOL_MAP }}"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "{{ .Values.kafka.environment.KAFKA_INTER_BROKER_LISTENER_NAME }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.kafka.environment.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "{{ .Values.kafka.environment.KAFKA_TRANSACTION_STATE_LOG_MIN_ISR }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ .Values.kafka.environment.KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR }}"
