apiVersion: v1
kind: Service
metadata:
  name: {{ include "pet-chart.fullname" . }}-mongodb
  labels:
    {{- include "pet-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
  selector:
    app: {{ include "pet-chart.fullname" . }}-mongodb
  clusterIP: none
