apiVersion: v1
kind: Service
metadata:
  name: {{ include "pet-chart.fullname" . }}-zookeeper
  labels:
    {{- include "pet-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: 2181
      protocol: TCP
      name: zookeeper
  selector:
    app: {{ include "pet-chart.fullname" . }}-zookeeper
